### ISSUE TITLE
Main not started...

### ISSUE THREAD

**Issue by edekemp** [SimBe-hub/PySubdiv#1]
I am just trying to run your code with PyCharm and a Conda interpreter (From Anaconda Navigator) this Python 3.9.
All your required packages have loaded. 

I believe I need to create a main.py fle as your README.md indicates ....  (below snippet) however I am not doing the main.py correctly.  Can you provide a proper startup file or new main.py? 

Regards,

Eric 

From README.md : 
# Quick Start

```python
from pysubdiv.main import main
from pysubdiv.main.data import files

# Create a simple Mesh by passing vertices and faces
# Create empty object or pass vertices and faces directly
mesh = main.Mesh()

**Comment by edekemp** [comment]
This is the error when running setup...

C:\MyPrograms\Anaconda3\envs\pythonProject\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2021.2.2\plugins\python-ce\helpers\pydev\pydevconsole.py" --mode=client --port=61266
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Working\\Papers\\Reviews\\reviews_2022\\Subdiv', 'C:/Working/Papers/Reviews/reviews_2022/Subdiv'])
PyDev console: starting.
Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] on win32
setup(
    name='PySubdiv', version=version, packages=find_packages(), install_requires=['networkx>=2.6.3','numpy>=1.21.4', 'pyacvd>=0.2.7',
                                                                                  'pyswarms>=1.3.0',
                                                                                  'pyvista>=0.32.1',
                                                                                  'scipy>=1.7.2'],
    url='',
    license='',
    author='Simon Bernard,  S. Mohammad Moulaeifard ',
    author_email='simon.bernard@rwth-aachen.de, Mohammad.Moulaeifard@cgre.rwth-aachen.de',
    description='An Open-source, Python-based software for fitting subdivision surfaces'
)
Traceback (most recent call last):
  File "<input>", line 2, in <module>
NameError: name 'setup' is not defined
mesh = main.Mesh()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'main' is not defined
